# Generated by Django 4.2.3 on 2023-10-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
